# -*- coding: utf-8 -*-

################################################################################
## Form generated from reading UI file 'MainWindowFlower.ui'
##
## Created by: Qt User Interface Compiler version 6.2.3
##
## WARNING! All changes made in this file will be lost when recompiling UI file!
################################################################################

from PySide6.QtCore import (QCoreApplication, QDate, QDateTime, QLocale,
    QMetaObject, QObject, QPoint, QRect,
    QSize, QTime, QUrl, Qt)
from PySide6.QtGui import (QAction, QBrush, QColor, QConicalGradient,
    QCursor, QFont, QFontDatabase, QGradient,
    QIcon, QImage, QKeySequence, QLinearGradient,
    QPainter, QPalette, QPixmap, QRadialGradient,
    QTransform)
from PySide6.QtWidgets import (QAbstractItemView, QApplication, QCheckBox, QComboBox,
    QFrame, QGroupBox, QHBoxLayout, QHeaderView,
    QLabel, QLineEdit, QMainWindow, QMenu,
    QMenuBar, QProgressBar, QPushButton, QSizePolicy,
    QSpacerItem, QSpinBox, QStatusBar, QTabWidget,
    QTableWidget, QTableWidgetItem, QTextEdit, QToolBar,
    QToolButton, QWidget)

from image_label import ImageLabel

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        if not MainWindow.objectName():
            MainWindow.setObjectName(u"MainWindow")
        MainWindow.resize(930, 670)
        sizePolicy = QSizePolicy(QSizePolicy.Preferred, QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(90)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(MainWindow.sizePolicy().hasHeightForWidth())
        MainWindow.setSizePolicy(sizePolicy)
        MainWindow.setMinimumSize(QSize(930, 670))
        MainWindow.setMaximumSize(QSize(930, 670))
        MainWindow.setContextMenuPolicy(Qt.CustomContextMenu)
        icon = QIcon()
        icon.addFile(u"images/AI\u8bc6\u522b.png", QSize(), QIcon.Normal, QIcon.Off)
        MainWindow.setWindowIcon(icon)
        MainWindow.setToolButtonStyle(Qt.ToolButtonTextBesideIcon)
        MainWindow.setDocumentMode(False)
        MainWindow.setTabShape(QTabWidget.Triangular)
        MainWindow.setUnifiedTitleAndToolBarOnMac(False)
        self.myModelAction = QAction(MainWindow)
        self.myModelAction.setObjectName(u"myModelAction")
        self.denseNet121Action = QAction(MainWindow)
        self.denseNet121Action.setObjectName(u"denseNet121Action")
        self.denseNet121Action.setCheckable(True)
        self.efficientNetB0Action = QAction(MainWindow)
        self.efficientNetB0Action.setObjectName(u"efficientNetB0Action")
        self.efficientNetB0Action.setCheckable(True)
        self.vGG19Action = QAction(MainWindow)
        self.vGG19Action.setObjectName(u"vGG19Action")
        self.vGG19Action.setCheckable(True)
        self.inceptionV3Action = QAction(MainWindow)
        self.inceptionV3Action.setObjectName(u"inceptionV3Action")
        self.inceptionV3Action.setCheckable(True)
        self.actionNew = QAction(MainWindow)
        self.actionNew.setObjectName(u"actionNew")
        icon1 = QIcon()
        icon1.addFile(u"images/\u65b0\u5efa.png", QSize(), QIcon.Normal, QIcon.Off)
        self.actionNew.setIcon(icon1)
        font = QFont()
        self.actionNew.setFont(font)
        self.actionNew.setShortcutContext(Qt.WidgetWithChildrenShortcut)
        self.actionOpen = QAction(MainWindow)
        self.actionOpen.setObjectName(u"actionOpen")
        icon2 = QIcon()
        icon2.addFile(u"images/\u6253\u5f00\u6587\u4ef6\u5939.png", QSize(), QIcon.Normal, QIcon.Off)
        self.actionOpen.setIcon(icon2)
        self.actionOpen.setFont(font)
        self.actionOpen.setShortcutContext(Qt.WidgetWithChildrenShortcut)
        self.actionClose = QAction(MainWindow)
        self.actionClose.setObjectName(u"actionClose")
        icon3 = QIcon()
        icon3.addFile(u"images/\u5173\u95ed.png", QSize(), QIcon.Normal, QIcon.Off)
        self.actionClose.setIcon(icon3)
        font1 = QFont()
        font1.setPointSize(10)
        self.actionClose.setFont(font1)
        self.actionCNN = QAction(MainWindow)
        self.actionCNN.setObjectName(u"actionCNN")
        icon4 = QIcon()
        icon4.addFile(u"images/\u6298\u7ebf\u56fe.png", QSize(), QIcon.Normal, QIcon.Off)
        self.actionCNN.setIcon(icon4)
        self.mobileNetV2Action = QAction(MainWindow)
        self.mobileNetV2Action.setObjectName(u"mobileNetV2Action")
        self.mobileNetV2Action.setCheckable(True)
        self.efficientNetB4Action = QAction(MainWindow)
        self.efficientNetB4Action.setObjectName(u"efficientNetB4Action")
        self.efficientNetB4Action.setCheckable(True)
        self.efficientNetB7Action = QAction(MainWindow)
        self.efficientNetB7Action.setObjectName(u"efficientNetB7Action")
        self.efficientNetB7Action.setCheckable(True)
        self.actionSave = QAction(MainWindow)
        self.actionSave.setObjectName(u"actionSave")
        icon5 = QIcon()
        icon5.addFile(u"images/\u4fdd\u5b58.png", QSize(), QIcon.Normal, QIcon.Off)
        self.actionSave.setIcon(icon5)
        self.actionClassify = QAction(MainWindow)
        self.actionClassify.setObjectName(u"actionClassify")
        icon6 = QIcon()
        icon6.addFile(u"images/\u4eba\u5de5\u667a\u80fd.png", QSize(), QIcon.Normal, QIcon.Off)
        self.actionClassify.setIcon(icon6)
        font2 = QFont()
        font2.setFamilies([u"\u5fae\u8f6f\u96c5\u9ed1"])
        font2.setPointSize(10)
        font2.setBold(True)
        font2.setUnderline(True)
        self.actionClassify.setFont(font2)
        self.actionAbout = QAction(MainWindow)
        self.actionAbout.setObjectName(u"actionAbout")
        icon7 = QIcon()
        icon7.addFile(u"images/\u5173\u4e8e.png", QSize(), QIcon.Normal, QIcon.Off)
        self.actionAbout.setIcon(icon7)
        self.actionMyStyle = QAction(MainWindow)
        self.actionMyStyle.setObjectName(u"actionMyStyle")
        self.actionMyStyle.setCheckable(True)
        self.actionUbuntuStyle = QAction(MainWindow)
        self.actionUbuntuStyle.setObjectName(u"actionUbuntuStyle")
        self.actionUbuntuStyle.setCheckable(True)
        self.actionAMOLED = QAction(MainWindow)
        self.actionAMOLED.setObjectName(u"actionAMOLED")
        self.actionAMOLED.setCheckable(True)
        self.actionAqua = QAction(MainWindow)
        self.actionAqua.setObjectName(u"actionAqua")
        self.actionAqua.setCheckable(True)
        self.actionConsoleStyle = QAction(MainWindow)
        self.actionConsoleStyle.setObjectName(u"actionConsoleStyle")
        self.actionConsoleStyle.setCheckable(True)
        self.actionElegantDark = QAction(MainWindow)
        self.actionElegantDark.setObjectName(u"actionElegantDark")
        self.actionElegantDark.setCheckable(True)
        self.actionMacOS = QAction(MainWindow)
        self.actionMacOS.setObjectName(u"actionMacOS")
        self.actionMacOS.setCheckable(True)
        self.actionManjaroMix = QAction(MainWindow)
        self.actionManjaroMix.setObjectName(u"actionManjaroMix")
        self.actionManjaroMix.setCheckable(True)
        self.actionMaterialDark = QAction(MainWindow)
        self.actionMaterialDark.setObjectName(u"actionMaterialDark")
        self.actionMaterialDark.setCheckable(True)
        self.efficientNetB2Action = QAction(MainWindow)
        self.efficientNetB2Action.setObjectName(u"efficientNetB2Action")
        self.efficientNetB2Action.setCheckable(True)
        self.centralwidget = QWidget(MainWindow)
        self.centralwidget.setObjectName(u"centralwidget")
        self.tabWidget = QTabWidget(self.centralwidget)
        self.tabWidget.setObjectName(u"tabWidget")
        self.tabWidget.setGeometry(QRect(0, 0, 931, 591))
        font3 = QFont()
        font3.setFamilies([u"\u5fae\u8f6f\u96c5\u9ed1"])
        font3.setPointSize(11)
        font3.setBold(False)
        self.tabWidget.setFont(font3)
        self.tabWidget.setMovable(True)
        self.tab1 = QWidget()
        self.tab1.setObjectName(u"tab1")
        self.groupBox = QGroupBox(self.tab1)
        self.groupBox.setObjectName(u"groupBox")
        self.groupBox.setGeometry(QRect(20, 13, 341, 341))
        font4 = QFont()
        font4.setFamilies([u"\u5fae\u8f6f\u96c5\u9ed1"])
        font4.setPointSize(10)
        font4.setBold(True)
        self.groupBox.setFont(font4)
        self.groupBox.setAlignment(Qt.AlignCenter)
        self.groupBox.setFlat(True)
        self.imageLabel = ImageLabel(self.groupBox)
        self.imageLabel.setObjectName(u"imageLabel")
        self.imageLabel.setGeometry(QRect(54, 120, 224, 224))
        self.imageLabel.setMinimumSize(QSize(224, 224))
        self.imageLabel.setMaximumSize(QSize(224, 224))
        font5 = QFont()
        font5.setFamilies([u"\u5fae\u8f6f\u96c5\u9ed1"])
        font5.setPointSize(16)
        font5.setBold(True)
        self.imageLabel.setFont(font5)
        self.imageLabel.setCursor(QCursor(Qt.PointingHandCursor))
        self.imageLabel.setAcceptDrops(True)
        self.imageLabel.setAutoFillBackground(False)
        self.imageLabel.setPixmap(QPixmap(u"images/\u6253\u5f00\u56fe\u7247.png"))
        self.imageLabel.setScaledContents(True)
        self.imageLabel.setAlignment(Qt.AlignCenter)
        self.imageLabel.setWordWrap(False)
        self.nameEdit = QLineEdit(self.groupBox)
        self.nameEdit.setObjectName(u"nameEdit")
        self.nameEdit.setGeometry(QRect(50, 82, 291, 25))
        font6 = QFont()
        font6.setFamilies([u"\u5fae\u8f6f\u96c5\u9ed1"])
        font6.setPointSize(9)
        font6.setBold(False)
        self.nameEdit.setFont(font6)
        self.nameEdit.setCursor(QCursor(Qt.IBeamCursor))
        self.nameEdit.setDragEnabled(True)
        self.nameEdit.setReadOnly(True)
        self.pathLabel = QLabel(self.groupBox)
        self.pathLabel.setObjectName(u"pathLabel")
        self.pathLabel.setGeometry(QRect(50, 23, 291, 50))
        sizePolicy1 = QSizePolicy(QSizePolicy.Expanding, QSizePolicy.Expanding)
        sizePolicy1.setHorizontalStretch(0)
        sizePolicy1.setVerticalStretch(0)
        sizePolicy1.setHeightForWidth(self.pathLabel.sizePolicy().hasHeightForWidth())
        self.pathLabel.setSizePolicy(sizePolicy1)
        self.pathLabel.setMinimumSize(QSize(0, 30))
        self.pathLabel.setMaximumSize(QSize(16777215, 50))
        font7 = QFont()
        font7.setFamilies([u"\u5fae\u8f6f\u96c5\u9ed1"])
        font7.setPointSize(8)
        font7.setBold(False)
        self.pathLabel.setFont(font7)
        self.pathLabel.setCursor(QCursor(Qt.WhatsThisCursor))
        self.pathLabel.setAlignment(Qt.AlignCenter)
        self.pathLabel.setWordWrap(True)
        self.pathLabel.setOpenExternalLinks(True)
        self.label_2 = QLabel(self.groupBox)
        self.label_2.setObjectName(u"label_2")
        self.label_2.setGeometry(QRect(12, 36, 31, 16))
        self.label_2.setFont(font6)
        self.chooseButton = QToolButton(self.groupBox)
        self.chooseButton.setObjectName(u"chooseButton")
        self.chooseButton.setGeometry(QRect(10, 78, 31, 31))
        self.chooseButton.setCursor(QCursor(Qt.PointingHandCursor))
        icon8 = QIcon()
        icon8.addFile(u"images/\u5bfc\u5165\u56fe\u7247.png", QSize(), QIcon.Normal, QIcon.Off)
        self.chooseButton.setIcon(icon8)
        self.chooseButton.setIconSize(QSize(28, 28))
        self.chooseButton.setAutoRaise(True)
        self.resetButton = QPushButton(self.groupBox)
        self.resetButton.setObjectName(u"resetButton")
        self.resetButton.setGeometry(QRect(310, 293, 31, 31))
        self.resetButton.setFont(font6)
        self.resetButton.setCursor(QCursor(Qt.PointingHandCursor))
        icon9 = QIcon()
        icon9.addFile(u"images/\u590d\u4f4d.png", QSize(), QIcon.Normal, QIcon.Off)
        self.resetButton.setIcon(icon9)
        self.resetButton.setIconSize(QSize(21, 21))
        self.resetButton.setFlat(True)
        self.groupBox_5 = QGroupBox(self.tab1)
        self.groupBox_5.setObjectName(u"groupBox_5")
        self.groupBox_5.setGeometry(QRect(380, 10, 501, 541))
        self.groupBox_5.setMinimumSize(QSize(0, 0))
        font8 = QFont()
        font8.setFamilies([u"\u5fae\u8f6f\u96c5\u9ed1"])
        font8.setPointSize(12)
        font8.setBold(True)
        self.groupBox_5.setFont(font8)
        self.groupBox_5.setAlignment(Qt.AlignCenter)
        self.groupBox_5.setFlat(True)
        self.layoutWidget = QWidget(self.groupBox_5)
        self.layoutWidget.setObjectName(u"layoutWidget")
        self.layoutWidget.setGeometry(QRect(20, 26, 471, 32))
        self.horizontalLayout_3 = QHBoxLayout(self.layoutWidget)
        self.horizontalLayout_3.setObjectName(u"horizontalLayout_3")
        self.horizontalLayout_3.setContentsMargins(0, 0, 0, 0)
        self.predictButton = QPushButton(self.layoutWidget)
        self.predictButton.setObjectName(u"predictButton")
        sizePolicy2 = QSizePolicy(QSizePolicy.Fixed, QSizePolicy.Expanding)
        sizePolicy2.setHorizontalStretch(0)
        sizePolicy2.setVerticalStretch(0)
        sizePolicy2.setHeightForWidth(self.predictButton.sizePolicy().hasHeightForWidth())
        self.predictButton.setSizePolicy(sizePolicy2)
        self.predictButton.setMinimumSize(QSize(60, 0))
        self.predictButton.setMaximumSize(QSize(60, 25))
        self.predictButton.setFont(font6)
        self.predictButton.setCursor(QCursor(Qt.PointingHandCursor))
        self.predictButton.setLayoutDirection(Qt.LeftToRight)
        self.predictButton.setAutoFillBackground(False)
        self.predictButton.setIcon(icon)
        self.predictButton.setIconSize(QSize(24, 24))
        self.predictButton.setFlat(True)

        self.horizontalLayout_3.addWidget(self.predictButton)

        self.resultLabel = QLabel(self.layoutWidget)
        self.resultLabel.setObjectName(u"resultLabel")
        sizePolicy3 = QSizePolicy(QSizePolicy.Preferred, QSizePolicy.Fixed)
        sizePolicy3.setHorizontalStretch(0)
        sizePolicy3.setVerticalStretch(0)
        sizePolicy3.setHeightForWidth(self.resultLabel.sizePolicy().hasHeightForWidth())
        self.resultLabel.setSizePolicy(sizePolicy3)
        self.resultLabel.setMinimumSize(QSize(20, 25))
        self.resultLabel.setMaximumSize(QSize(600, 25))
        self.resultLabel.setFont(font6)
        self.resultLabel.setScaledContents(True)
        self.resultLabel.setAlignment(Qt.AlignLeading|Qt.AlignLeft|Qt.AlignVCenter)

        self.horizontalLayout_3.addWidget(self.resultLabel)

        self.resultLabel_2 = QLabel(self.layoutWidget)
        self.resultLabel_2.setObjectName(u"resultLabel_2")
        sizePolicy4 = QSizePolicy(QSizePolicy.Fixed, QSizePolicy.Fixed)
        sizePolicy4.setHorizontalStretch(0)
        sizePolicy4.setVerticalStretch(0)
        sizePolicy4.setHeightForWidth(self.resultLabel_2.sizePolicy().hasHeightForWidth())
        self.resultLabel_2.setSizePolicy(sizePolicy4)
        self.resultLabel_2.setMinimumSize(QSize(25, 25))
        self.resultLabel_2.setMaximumSize(QSize(25, 25))
        self.resultLabel_2.setScaledContents(True)
        self.resultLabel_2.setAlignment(Qt.AlignLeading|Qt.AlignLeft|Qt.AlignVCenter)

        self.horizontalLayout_3.addWidget(self.resultLabel_2)

        self.horizontalSpacer_3 = QSpacerItem(0, 20, QSizePolicy.Expanding, QSizePolicy.Minimum)

        self.horizontalLayout_3.addItem(self.horizontalSpacer_3)

        self.label_4 = QLabel(self.groupBox_5)
        self.label_4.setObjectName(u"label_4")
        self.label_4.setGeometry(QRect(22, 75, 471, 461))
        self.label_4.setPixmap(QPixmap(u"images/rongzi.png"))
        self.label_4.setScaledContents(False)
        self.label_4.setAlignment(Qt.AlignCenter)
        self.resultLabel_3 = QLabel(self.groupBox_5)
        self.resultLabel_3.setObjectName(u"resultLabel_3")
        self.resultLabel_3.setGeometry(QRect(20, 65, 471, 31))
        font9 = QFont()
        font9.setFamilies([u"\u5fae\u8f6f\u96c5\u9ed1"])
        font9.setPointSize(10)
        font9.setBold(False)
        self.resultLabel_3.setFont(font9)
        self.resultLabel_3.setTextFormat(Qt.RichText)
        self.line_2 = QFrame(self.tab1)
        self.line_2.setObjectName(u"line_2")
        self.line_2.setGeometry(QRect(357, 21, 30, 531))
        self.line_2.setFrameShape(QFrame.VLine)
        self.line_2.setFrameShadow(QFrame.Sunken)
        self.clearButton = QToolButton(self.tab1)
        self.clearButton.setObjectName(u"clearButton")
        self.clearButton.setGeometry(QRect(20, 336, 31, 31))
        self.clearButton.setCursor(QCursor(Qt.PointingHandCursor))
        icon10 = QIcon()
        icon10.addFile(u"images/\u6e05\u9664.png", QSize(), QIcon.Normal, QIcon.Off)
        self.clearButton.setIcon(icon10)
        self.clearButton.setIconSize(QSize(40, 40))
        self.clearButton.setAutoRaise(True)
        self.cutButton = QPushButton(self.tab1)
        self.cutButton.setObjectName(u"cutButton")
        self.cutButton.setGeometry(QRect(330, 337, 31, 30))
        self.cutButton.setFont(font6)
        self.cutButton.setCursor(QCursor(Qt.PointingHandCursor))
        icon11 = QIcon()
        icon11.addFile(u"images/\u88c1\u526a\u65cb\u8f6c.png", QSize(), QIcon.Normal, QIcon.Off)
        self.cutButton.setIcon(icon11)
        self.cutButton.setIconSize(QSize(24, 24))
        self.cutButton.setFlat(True)
        self.line_3 = QFrame(self.tab1)
        self.line_3.setObjectName(u"line_3")
        self.line_3.setGeometry(QRect(20, 362, 344, 20))
        self.line_3.setFrameShape(QFrame.HLine)
        self.line_3.setFrameShadow(QFrame.Sunken)
        self.tabWidget_2 = QTabWidget(self.tab1)
        self.tabWidget_2.setObjectName(u"tabWidget_2")
        self.tabWidget_2.setGeometry(QRect(20, 372, 347, 181))
        self.tabWidget_2.setFont(font6)
        self.tab = QWidget()
        self.tab.setObjectName(u"tab")
        self.imageTextEdit = QTextEdit(self.tab)
        self.imageTextEdit.setObjectName(u"imageTextEdit")
        self.imageTextEdit.setGeometry(QRect(0, 0, 336, 151))
        self.imageTextEdit.setFont(font6)
        self.imageTextEdit.viewport().setProperty("cursor", QCursor(Qt.IBeamCursor))
        self.imageTextEdit.setReadOnly(True)
        self.tabWidget_2.addTab(self.tab, "")
        self.tab_2 = QWidget()
        self.tab_2.setObjectName(u"tab_2")
        self.saveButton = QPushButton(self.tab_2)
        self.saveButton.setObjectName(u"saveButton")
        self.saveButton.setGeometry(QRect(185, 113, 151, 31))
        self.saveButton.setFont(font6)
        self.saveButton.setCursor(QCursor(Qt.PointingHandCursor))
        icon12 = QIcon()
        icon12.addFile(u"images/\u4fdd\u5b58\u56fe\u7247.png", QSize(), QIcon.Normal, QIcon.Off)
        self.saveButton.setIcon(icon12)
        self.saveButton.setIconSize(QSize(20, 20))
        self.saveNameEdit = QLineEdit(self.tab_2)
        self.saveNameEdit.setObjectName(u"saveNameEdit")
        self.saveNameEdit.setGeometry(QRect(60, 10, 111, 25))
        self.saveNameEdit.setFont(font6)
        self.saveNameEdit.setCursor(QCursor(Qt.IBeamCursor))
        self.saveNameEdit.setFrame(True)
        self.label_3 = QLabel(self.tab_2)
        self.label_3.setObjectName(u"label_3")
        self.label_3.setGeometry(QRect(12, 14, 41, 16))
        self.savePathTextEdit = QTextEdit(self.tab_2)
        self.savePathTextEdit.setObjectName(u"savePathTextEdit")
        self.savePathTextEdit.setGeometry(QRect(10, 67, 161, 81))
        self.savePathTextEdit.setFont(font9)
        self.savePathTextEdit.viewport().setProperty("cursor", QCursor(Qt.ArrowCursor))
        self.savePathTextEdit.setVerticalScrollBarPolicy(Qt.ScrollBarAlwaysOff)
        self.label_5 = QLabel(self.tab_2)
        self.label_5.setObjectName(u"label_5")
        self.label_5.setGeometry(QRect(11, 43, 61, 16))
        self.getDirectoryButton_2 = QToolButton(self.tab_2)
        self.getDirectoryButton_2.setObjectName(u"getDirectoryButton_2")
        self.getDirectoryButton_2.setGeometry(QRect(73, 41, 24, 22))
        self.getDirectoryButton_2.setCursor(QCursor(Qt.PointingHandCursor))
        icon13 = QIcon()
        icon13.addFile(u"images/\u6587\u4ef6\u5939.png", QSize(), QIcon.Normal, QIcon.Off)
        self.getDirectoryButton_2.setIcon(icon13)
        self.getDirectoryButton_2.setIconSize(QSize(24, 24))
        self.getDirectoryButton_2.setAutoRaise(True)
        self.comboBox = QComboBox(self.tab_2)
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox.setObjectName(u"comboBox")
        self.comboBox.setGeometry(QRect(197, 5, 131, 22))
        self.comboBox.setMaxVisibleItems(5)
        self.comboBox.setFrame(True)
        self.comboBox_2 = QComboBox(self.tab_2)
        self.comboBox_2.addItem("")
        self.comboBox_2.addItem("")
        self.comboBox_2.addItem("")
        self.comboBox_2.addItem("")
        self.comboBox_2.addItem("")
        self.comboBox_2.addItem("")
        self.comboBox_2.addItem("")
        self.comboBox_2.setObjectName(u"comboBox_2")
        self.comboBox_2.setGeometry(QRect(197, 40, 131, 22))
        self.comboBox_2.setMaxVisibleItems(5)
        self.comboBox_2.setFrame(True)
        self.spinBox_height = QSpinBox(self.tab_2)
        self.spinBox_height.setObjectName(u"spinBox_height")
        self.spinBox_height.setGeometry(QRect(291, 75, 42, 22))
        self.spinBox_height.setAcceptDrops(True)
        self.spinBox_height.setMaximum(1000)
        self.spinBox_width = QSpinBox(self.tab_2)
        self.spinBox_width.setObjectName(u"spinBox_width")
        self.spinBox_width.setGeometry(QRect(236, 75, 42, 22))
        self.spinBox_width.setAcceptDrops(True)
        self.spinBox_width.setMaximum(1000)
        self.label_6 = QLabel(self.tab_2)
        self.label_6.setObjectName(u"label_6")
        self.label_6.setGeometry(QRect(280, 78, 16, 16))
        self.label_6.setFont(font4)
        self.label_res = QLabel(self.tab_2)
        self.label_res.setObjectName(u"label_res")
        self.label_res.setGeometry(QRect(187, 79, 41, 16))
        self.tabWidget_2.addTab(self.tab_2, "")
        self.tabWidget.addTab(self.tab1, "")
        self.tab2 = QWidget()
        self.tab2.setObjectName(u"tab2")
        self.tableWidget = QTableWidget(self.tab2)
        if (self.tableWidget.columnCount() < 3):
            self.tableWidget.setColumnCount(3)
        font10 = QFont()
        font10.setFamilies([u"\u534e\u6587\u7ec6\u9ed1"])
        font10.setPointSize(11)
        font10.setBold(True)
        __qtablewidgetitem = QTableWidgetItem()
        __qtablewidgetitem.setFont(font10);
        __qtablewidgetitem.setIcon(icon13);
        self.tableWidget.setHorizontalHeaderItem(0, __qtablewidgetitem)
        icon14 = QIcon()
        icon14.addFile(u"images/\u56fe\u7247.png", QSize(), QIcon.Normal, QIcon.Off)
        __qtablewidgetitem1 = QTableWidgetItem()
        __qtablewidgetitem1.setFont(font10);
        __qtablewidgetitem1.setIcon(icon14);
        self.tableWidget.setHorizontalHeaderItem(1, __qtablewidgetitem1)
        icon15 = QIcon()
        icon15.addFile(u"images/\u82b1\u6735.png", QSize(), QIcon.Normal, QIcon.Off)
        __qtablewidgetitem2 = QTableWidgetItem()
        __qtablewidgetitem2.setFont(font10);
        __qtablewidgetitem2.setIcon(icon15);
        self.tableWidget.setHorizontalHeaderItem(2, __qtablewidgetitem2)
        self.tableWidget.setObjectName(u"tableWidget")
        self.tableWidget.setGeometry(QRect(0, 0, 431, 521))
        self.tableWidget.setContextMenuPolicy(Qt.CustomContextMenu)
        self.tableWidget.setEditTriggers(QAbstractItemView.NoEditTriggers)
        self.tableWidget.setAlternatingRowColors(True)
        self.tableWidget.setSelectionBehavior(QAbstractItemView.SelectRows)
        self.tableWidget.setIconSize(QSize(24, 24))
        self.tableWidget.setShowGrid(True)
        self.tableWidget.setSortingEnabled(True)
        self.tableWidget.setColumnCount(3)
        self.tableWidget.horizontalHeader().setMinimumSectionSize(30)
        self.tableWidget.horizontalHeader().setDefaultSectionSize(130)
        self.tableWidget.verticalHeader().setVisible(True)
        self.tableWidget.verticalHeader().setDefaultSectionSize(30)
        self.tableWidget.verticalHeader().setProperty("showSortIndicator", True)
        self.clearTableButton = QPushButton(self.tab2)
        self.clearTableButton.setObjectName(u"clearTableButton")
        self.clearTableButton.setGeometry(QRect(404, 524, 30, 30))
        sizePolicy4.setHeightForWidth(self.clearTableButton.sizePolicy().hasHeightForWidth())
        self.clearTableButton.setSizePolicy(sizePolicy4)
        self.clearTableButton.setMinimumSize(QSize(30, 30))
        self.clearTableButton.setMaximumSize(QSize(30, 30))
        self.clearTableButton.setCursor(QCursor(Qt.PointingHandCursor))
        icon16 = QIcon()
        icon16.addFile(u"images/\u5220\u9664.png", QSize(), QIcon.Normal, QIcon.Off)
        self.clearTableButton.setIcon(icon16)
        self.clearTableButton.setIconSize(QSize(24, 24))
        self.clearTableButton.setFlat(True)
        self.groupBox_2 = QGroupBox(self.tab2)
        self.groupBox_2.setObjectName(u"groupBox_2")
        self.groupBox_2.setGeometry(QRect(450, 10, 441, 151))
        font11 = QFont()
        font11.setFamilies([u"\u5fae\u8f6f\u96c5\u9ed1"])
        font11.setPointSize(11)
        font11.setBold(True)
        self.groupBox_2.setFont(font11)
        self.groupBox_2.setAlignment(Qt.AlignCenter)
        self.groupBox_2.setFlat(True)
        self.batchPredictButton = QPushButton(self.groupBox_2)
        self.batchPredictButton.setObjectName(u"batchPredictButton")
        self.batchPredictButton.setGeometry(QRect(10, 29, 110, 25))
        sizePolicy2.setHeightForWidth(self.batchPredictButton.sizePolicy().hasHeightForWidth())
        self.batchPredictButton.setSizePolicy(sizePolicy2)
        self.batchPredictButton.setMinimumSize(QSize(110, 25))
        self.batchPredictButton.setMaximumSize(QSize(110, 25))
        self.batchPredictButton.setFont(font6)
        self.batchPredictButton.setCursor(QCursor(Qt.PointingHandCursor))
        icon17 = QIcon()
        icon17.addFile(u"images/Image \u56fe\u50cf\u8bc6\u522b.png", QSize(), QIcon.Normal, QIcon.Off)
        self.batchPredictButton.setIcon(icon17)
        self.batchPredictButton.setIconSize(QSize(24, 24))
        self.batchPredictButton.setFlat(False)
        self.progressBar2 = QProgressBar(self.groupBox_2)
        self.progressBar2.setObjectName(u"progressBar2")
        self.progressBar2.setGeometry(QRect(130, 30, 291, 23))
        self.progressBar2.setFont(font6)
        self.progressBar2.setValue(0)
        self.label = QLabel(self.groupBox_2)
        self.label.setObjectName(u"label")
        self.label.setGeometry(QRect(12, 81, 60, 16))
        self.label.setFont(font6)
        self.savePathLineEdit = QLineEdit(self.groupBox_2)
        self.savePathLineEdit.setObjectName(u"savePathLineEdit")
        self.savePathLineEdit.setGeometry(QRect(78, 76, 321, 26))
        self.savePathLineEdit.setFont(font6)
        self.getDirectoryButton = QToolButton(self.groupBox_2)
        self.getDirectoryButton.setObjectName(u"getDirectoryButton")
        self.getDirectoryButton.setGeometry(QRect(400, 74, 31, 30))
        self.getDirectoryButton.setCursor(QCursor(Qt.PointingHandCursor))
        self.getDirectoryButton.setIcon(icon13)
        self.getDirectoryButton.setIconSize(QSize(24, 24))
        self.getDirectoryButton.setAutoRaise(True)
        self.batchExportButton = QPushButton(self.groupBox_2)
        self.batchExportButton.setObjectName(u"batchExportButton")
        self.batchExportButton.setGeometry(QRect(343, 112, 85, 30))
        sizePolicy2.setHeightForWidth(self.batchExportButton.sizePolicy().hasHeightForWidth())
        self.batchExportButton.setSizePolicy(sizePolicy2)
        self.batchExportButton.setMinimumSize(QSize(85, 30))
        self.batchExportButton.setMaximumSize(QSize(85, 30))
        self.batchExportButton.setFont(font6)
        self.batchExportButton.setCursor(QCursor(Qt.PointingHandCursor))
        self.batchExportButton.setLayoutDirection(Qt.LeftToRight)
        self.batchExportButton.setAutoFillBackground(False)
        icon18 = QIcon()
        icon18.addFile(u"images/\u6279\u91cf\u5bfc\u51fa.png", QSize(), QIcon.Normal, QIcon.Off)
        self.batchExportButton.setIcon(icon18)
        self.batchExportButton.setIconSize(QSize(24, 24))
        self.batchExportButton.setFlat(False)
        self.convertModeCheckBox = QCheckBox(self.groupBox_2)
        self.convertModeCheckBox.setObjectName(u"convertModeCheckBox")
        self.convertModeCheckBox.setGeometry(QRect(189, 117, 81, 20))
        self.convertModeCheckBox.setFont(font6)
        self.batchRenameCheckBox = QCheckBox(self.groupBox_2)
        self.batchRenameCheckBox.setObjectName(u"batchRenameCheckBox")
        self.batchRenameCheckBox.setGeometry(QRect(271, 117, 61, 20))
        self.batchRenameCheckBox.setFont(font6)
        self.spinBox_width_2 = QSpinBox(self.groupBox_2)
        self.spinBox_width_2.setObjectName(u"spinBox_width_2")
        self.spinBox_width_2.setGeometry(QRect(70, 116, 42, 22))
        self.spinBox_width_2.setFont(font6)
        self.spinBox_width_2.setAcceptDrops(True)
        self.spinBox_width_2.setMaximum(1000)
        self.label_res_2 = QLabel(self.groupBox_2)
        self.label_res_2.setObjectName(u"label_res_2")
        self.label_res_2.setGeometry(QRect(19, 119, 41, 16))
        self.label_res_2.setFont(font6)
        self.label_9 = QLabel(self.groupBox_2)
        self.label_9.setObjectName(u"label_9")
        self.label_9.setGeometry(QRect(115, 118, 16, 16))
        self.label_9.setFont(font4)
        self.spinBox_height_2 = QSpinBox(self.groupBox_2)
        self.spinBox_height_2.setObjectName(u"spinBox_height_2")
        self.spinBox_height_2.setGeometry(QRect(130, 116, 42, 22))
        self.spinBox_height_2.setFont(font6)
        self.spinBox_height_2.setAcceptDrops(True)
        self.spinBox_height_2.setMaximum(1000)
        self.batchImportLabel = QLabel(self.tab2)
        self.batchImportLabel.setObjectName(u"batchImportLabel")
        self.batchImportLabel.setGeometry(QRect(9, 531, 351, 21))
        font12 = QFont()
        font12.setFamilies([u"\u534e\u6587\u7ec6\u9ed1"])
        font12.setPointSize(11)
        font12.setBold(False)
        self.batchImportLabel.setFont(font12)
        self.batchChooseButton = QPushButton(self.tab2)
        self.batchChooseButton.setObjectName(u"batchChooseButton")
        self.batchChooseButton.setGeometry(QRect(370, 524, 30, 30))
        sizePolicy4.setHeightForWidth(self.batchChooseButton.sizePolicy().hasHeightForWidth())
        self.batchChooseButton.setSizePolicy(sizePolicy4)
        self.batchChooseButton.setMinimumSize(QSize(30, 30))
        self.batchChooseButton.setMaximumSize(QSize(30, 30))
        self.batchChooseButton.setCursor(QCursor(Qt.PointingHandCursor))
        icon19 = QIcon()
        icon19.addFile(u"images/\u5bfc\u5165.png", QSize(), QIcon.Normal, QIcon.Off)
        self.batchChooseButton.setIcon(icon19)
        self.batchChooseButton.setIconSize(QSize(24, 24))
        self.batchChooseButton.setFlat(True)
        self.statisticsTextEdit = QTextEdit(self.tab2)
        self.statisticsTextEdit.setObjectName(u"statisticsTextEdit")
        self.statisticsTextEdit.setGeometry(QRect(450, 170, 441, 381))
        self.statisticsTextEdit.setFont(font9)
        self.statisticsTextEdit.setReadOnly(True)
        self.statisticsButton = QPushButton(self.tab2)
        self.statisticsButton.setObjectName(u"statisticsButton")
        self.statisticsButton.setGeometry(QRect(834, 520, 30, 30))
        sizePolicy4.setHeightForWidth(self.statisticsButton.sizePolicy().hasHeightForWidth())
        self.statisticsButton.setSizePolicy(sizePolicy4)
        self.statisticsButton.setMinimumSize(QSize(30, 30))
        self.statisticsButton.setMaximumSize(QSize(30, 30))
        self.statisticsButton.setCursor(QCursor(Qt.PointingHandCursor))
        icon20 = QIcon()
        icon20.addFile(u"images/\u5806\u53e0\u67f1\u72b6\u56fe.png", QSize(), QIcon.Normal, QIcon.Off)
        self.statisticsButton.setIcon(icon20)
        self.statisticsButton.setIconSize(QSize(24, 24))
        self.statisticsButton.setFlat(True)
        self.tabWidget.addTab(self.tab2, "")
        self.groupBox_2.raise_()
        self.tableWidget.raise_()
        self.clearTableButton.raise_()
        self.batchImportLabel.raise_()
        self.batchChooseButton.raise_()
        self.statisticsTextEdit.raise_()
        self.statisticsButton.raise_()
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QMenuBar(MainWindow)
        self.menubar.setObjectName(u"menubar")
        self.menubar.setGeometry(QRect(0, 0, 930, 30))
        sizePolicy5 = QSizePolicy(QSizePolicy.MinimumExpanding, QSizePolicy.Minimum)
        sizePolicy5.setHorizontalStretch(0)
        sizePolicy5.setVerticalStretch(25)
        sizePolicy5.setHeightForWidth(self.menubar.sizePolicy().hasHeightForWidth())
        self.menubar.setSizePolicy(sizePolicy5)
        self.menubar.setMinimumSize(QSize(0, 30))
        self.menubar.setMaximumSize(QSize(16777215, 30))
        font13 = QFont()
        font13.setFamilies([u"Microsoft YaHei"])
        font13.setPointSize(10)
        font13.setBold(False)
        self.menubar.setFont(font13)
        self.menubar.setDefaultUp(False)
        self.menubar.setNativeMenuBar(False)
        self.menu = QMenu(self.menubar)
        self.menu.setObjectName(u"menu")
        self.menu.setSeparatorsCollapsible(True)
        self.menu.setToolTipsVisible(True)
        self.menu_2 = QMenu(self.menubar)
        self.menu_2.setObjectName(u"menu_2")
        self.menu_style = QMenu(self.menu_2)
        self.menu_style.setObjectName(u"menu_style")
        icon21 = QIcon()
        icon21.addFile(u"images/\u4e3b\u9898.png", QSize(), QIcon.Normal, QIcon.Off)
        self.menu_style.setIcon(icon21)
        self.menu_M = QMenu(self.menubar)
        self.menu_M.setObjectName(u"menu_M")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QStatusBar(MainWindow)
        self.statusbar.setObjectName(u"statusbar")
        MainWindow.setStatusBar(self.statusbar)
        self.toolBar = QToolBar(MainWindow)
        self.toolBar.setObjectName(u"toolBar")
        self.toolBar.setEnabled(True)
        self.toolBar.setCursor(QCursor(Qt.PointingHandCursor))
        self.toolBar.setMovable(False)
        self.toolBar.setToolButtonStyle(Qt.ToolButtonIconOnly)
        MainWindow.addToolBar(Qt.TopToolBarArea, self.toolBar)
        QWidget.setTabOrder(self.chooseButton, self.clearButton)
        QWidget.setTabOrder(self.clearButton, self.cutButton)
        QWidget.setTabOrder(self.cutButton, self.resetButton)
        QWidget.setTabOrder(self.resetButton, self.getDirectoryButton_2)
        QWidget.setTabOrder(self.getDirectoryButton_2, self.predictButton)
        QWidget.setTabOrder(self.predictButton, self.nameEdit)
        QWidget.setTabOrder(self.nameEdit, self.tabWidget)
        QWidget.setTabOrder(self.tabWidget, self.batchChooseButton)
        QWidget.setTabOrder(self.batchChooseButton, self.clearTableButton)
        QWidget.setTabOrder(self.clearTableButton, self.batchPredictButton)
        QWidget.setTabOrder(self.batchPredictButton, self.getDirectoryButton)
        QWidget.setTabOrder(self.getDirectoryButton, self.convertModeCheckBox)
        QWidget.setTabOrder(self.convertModeCheckBox, self.batchRenameCheckBox)
        QWidget.setTabOrder(self.batchRenameCheckBox, self.batchExportButton)
        QWidget.setTabOrder(self.batchExportButton, self.statisticsButton)
        QWidget.setTabOrder(self.statisticsButton, self.tableWidget)
        QWidget.setTabOrder(self.tableWidget, self.statisticsTextEdit)
        QWidget.setTabOrder(self.statisticsTextEdit, self.savePathLineEdit)

        self.menubar.addAction(self.menu.menuAction())
        self.menubar.addAction(self.menu_M.menuAction())
        self.menubar.addAction(self.menu_2.menuAction())
        self.menu.addAction(self.actionOpen)
        self.menu.addAction(self.actionSave)
        self.menu.addSeparator()
        self.menu.addAction(self.actionClose)
        self.menu_2.addAction(self.actionAbout)
        self.menu_2.addSeparator()
        self.menu_2.addAction(self.menu_style.menuAction())
        self.menu_style.addAction(self.actionUbuntuStyle)
        self.menu_style.addAction(self.actionAMOLED)
        self.menu_style.addAction(self.actionAqua)
        self.menu_style.addAction(self.actionConsoleStyle)
        self.menu_style.addAction(self.actionElegantDark)
        self.menu_style.addAction(self.actionMacOS)
        self.menu_style.addAction(self.actionManjaroMix)
        self.menu_style.addAction(self.actionMaterialDark)
        self.menu_style.addAction(self.actionMyStyle)
        self.menu_M.addAction(self.efficientNetB7Action)
        self.menu_M.addAction(self.efficientNetB4Action)
        self.menu_M.addAction(self.efficientNetB2Action)
        self.menu_M.addAction(self.efficientNetB0Action)
        self.menu_M.addSeparator()
        self.menu_M.addAction(self.mobileNetV2Action)
        self.menu_M.addAction(self.denseNet121Action)
        self.menu_M.addAction(self.inceptionV3Action)
        self.menu_M.addAction(self.vGG19Action)
        self.menu_M.addSeparator()
        self.menu_M.addAction(self.actionCNN)
        self.toolBar.addAction(self.actionOpen)
        self.toolBar.addAction(self.actionSave)
        self.toolBar.addSeparator()
        self.toolBar.addAction(self.actionCNN)
        self.toolBar.addSeparator()
        self.toolBar.addAction(self.actionClassify)

        self.retranslateUi(MainWindow)
        self.savePathLineEdit.editingFinished.connect(self.batchExportButton.click)

        self.tabWidget.setCurrentIndex(0)
        self.tabWidget_2.setCurrentIndex(0)
        self.comboBox.setCurrentIndex(-1)
        self.comboBox_2.setCurrentIndex(-1)


        QMetaObject.connectSlotsByName(MainWindow)
    # setupUi

    def retranslateUi(self, MainWindow):
        MainWindow.setWindowTitle(QCoreApplication.translate("MainWindow", u"\u82b1\u6735\u5206\u7c7b", None))
        self.myModelAction.setText(QCoreApplication.translate("MainWindow", u"MyModel", None))
#if QT_CONFIG(tooltip)
        self.myModelAction.setToolTip(QCoreApplication.translate("MainWindow", u"MyModel", None))
#endif // QT_CONFIG(tooltip)
        self.denseNet121Action.setText(QCoreApplication.translate("MainWindow", u"DenseNet121", None))
#if QT_CONFIG(tooltip)
        self.denseNet121Action.setToolTip(QCoreApplication.translate("MainWindow", u"DenseNet121", None))
#endif // QT_CONFIG(tooltip)
#if QT_CONFIG(shortcut)
        self.denseNet121Action.setShortcut(QCoreApplication.translate("MainWindow", u"Ctrl+Alt+D", None))
#endif // QT_CONFIG(shortcut)
        self.efficientNetB0Action.setText(QCoreApplication.translate("MainWindow", u"EfficientNetB0", None))
#if QT_CONFIG(tooltip)
        self.efficientNetB0Action.setToolTip(QCoreApplication.translate("MainWindow", u"EfficientNetB0", None))
#endif // QT_CONFIG(tooltip)
#if QT_CONFIG(shortcut)
        self.efficientNetB0Action.setShortcut(QCoreApplication.translate("MainWindow", u"Ctrl+Alt+0", None))
#endif // QT_CONFIG(shortcut)
        self.vGG19Action.setText(QCoreApplication.translate("MainWindow", u"VGG19", None))
#if QT_CONFIG(tooltip)
        self.vGG19Action.setToolTip(QCoreApplication.translate("MainWindow", u"VGG19", None))
#endif // QT_CONFIG(tooltip)
#if QT_CONFIG(shortcut)
        self.vGG19Action.setShortcut(QCoreApplication.translate("MainWindow", u"Ctrl+Alt+G", None))
#endif // QT_CONFIG(shortcut)
        self.inceptionV3Action.setText(QCoreApplication.translate("MainWindow", u"InceptionV3", None))
#if QT_CONFIG(tooltip)
        self.inceptionV3Action.setToolTip(QCoreApplication.translate("MainWindow", u"InceptionV3", None))
#endif // QT_CONFIG(tooltip)
#if QT_CONFIG(shortcut)
        self.inceptionV3Action.setShortcut(QCoreApplication.translate("MainWindow", u"Ctrl+Alt+I", None))
#endif // QT_CONFIG(shortcut)
        self.actionNew.setText(QCoreApplication.translate("MainWindow", u"\u65b0\u5efa(&N)", None))
#if QT_CONFIG(tooltip)
        self.actionNew.setToolTip(QCoreApplication.translate("MainWindow", u"\u65b0\u5efa", None))
#endif // QT_CONFIG(tooltip)
#if QT_CONFIG(shortcut)
        self.actionNew.setShortcut(QCoreApplication.translate("MainWindow", u"Ctrl+N", None))
#endif // QT_CONFIG(shortcut)
        self.actionOpen.setText(QCoreApplication.translate("MainWindow", u"\u6253\u5f00(&O)", None))
#if QT_CONFIG(tooltip)
        self.actionOpen.setToolTip(QCoreApplication.translate("MainWindow", u"\u6253\u5f00", None))
#endif // QT_CONFIG(tooltip)
#if QT_CONFIG(shortcut)
        self.actionOpen.setShortcut(QCoreApplication.translate("MainWindow", u"Ctrl+O", None))
#endif // QT_CONFIG(shortcut)
        self.actionClose.setText(QCoreApplication.translate("MainWindow", u"\u5173\u95ed(&C)", None))
        self.actionCNN.setText(QCoreApplication.translate("MainWindow", u"\u6a21\u578b\u7edf\u8ba1", None))
#if QT_CONFIG(tooltip)
        self.actionCNN.setToolTip(QCoreApplication.translate("MainWindow", u"\u6a21\u578b\u7edf\u8ba1", None))
#endif // QT_CONFIG(tooltip)
        self.mobileNetV2Action.setText(QCoreApplication.translate("MainWindow", u"MobileNetV2", None))
#if QT_CONFIG(tooltip)
        self.mobileNetV2Action.setToolTip(QCoreApplication.translate("MainWindow", u"MobileNetV2", None))
#endif // QT_CONFIG(tooltip)
#if QT_CONFIG(shortcut)
        self.mobileNetV2Action.setShortcut(QCoreApplication.translate("MainWindow", u"Ctrl+Alt+M", None))
#endif // QT_CONFIG(shortcut)
        self.efficientNetB4Action.setText(QCoreApplication.translate("MainWindow", u"EfficientNetB4", None))
#if QT_CONFIG(tooltip)
        self.efficientNetB4Action.setToolTip(QCoreApplication.translate("MainWindow", u"EfficientNetB4", None))
#endif // QT_CONFIG(tooltip)
#if QT_CONFIG(shortcut)
        self.efficientNetB4Action.setShortcut(QCoreApplication.translate("MainWindow", u"Ctrl+Alt+4", None))
#endif // QT_CONFIG(shortcut)
        self.efficientNetB7Action.setText(QCoreApplication.translate("MainWindow", u"EfficientNetB7", None))
#if QT_CONFIG(tooltip)
        self.efficientNetB7Action.setToolTip(QCoreApplication.translate("MainWindow", u"EfficientNetB7", None))
#endif // QT_CONFIG(tooltip)
#if QT_CONFIG(shortcut)
        self.efficientNetB7Action.setShortcut(QCoreApplication.translate("MainWindow", u"Ctrl+Alt+7", None))
#endif // QT_CONFIG(shortcut)
        self.actionSave.setText(QCoreApplication.translate("MainWindow", u"\u4fdd\u5b58(&S)", None))
#if QT_CONFIG(tooltip)
        self.actionSave.setToolTip(QCoreApplication.translate("MainWindow", u"\u4fdd\u5b58", None))
#endif // QT_CONFIG(tooltip)
#if QT_CONFIG(shortcut)
        self.actionSave.setShortcut(QCoreApplication.translate("MainWindow", u"Ctrl+S", None))
#endif // QT_CONFIG(shortcut)
        self.actionClassify.setText(QCoreApplication.translate("MainWindow", u"\u6df1\u5ea6\u8bc6\u522b", None))
#if QT_CONFIG(tooltip)
        self.actionClassify.setToolTip(QCoreApplication.translate("MainWindow", u"<html><head/><body><p><span style=\" font-size:10pt;\">\u5bf9\u5f53\u524d\u56fe\u7247\u8fdb\u884c</span><span style=\" font-size:10pt; font-weight:700; color:#ff0000;\">\u591a\u6a21\u578b</span><span style=\" font-size:10pt; font-weight:700; color:#ff0000;\">\u52a0\u6743</span><span style=\" font-size:10pt;\">\u6df1\u5ea6\u8bc6\u522b</span></p></body></html>", None))
#endif // QT_CONFIG(tooltip)
        self.actionAbout.setText(QCoreApplication.translate("MainWindow", u"\u5173\u4e8e", None))
        self.actionMyStyle.setText(QCoreApplication.translate("MainWindow", u"\u6e10\u53d8\u84dd", None))
        self.actionUbuntuStyle.setText(QCoreApplication.translate("MainWindow", u"Ubuntu", None))
        self.actionAMOLED.setText(QCoreApplication.translate("MainWindow", u"AMOLED", None))
        self.actionAqua.setText(QCoreApplication.translate("MainWindow", u"Aqua", None))
        self.actionConsoleStyle.setText(QCoreApplication.translate("MainWindow", u"ConsoleStyle", None))
        self.actionElegantDark.setText(QCoreApplication.translate("MainWindow", u"ElegantDark", None))
        self.actionMacOS.setText(QCoreApplication.translate("MainWindow", u"MacOS", None))
        self.actionManjaroMix.setText(QCoreApplication.translate("MainWindow", u"ManjaroMix", None))
        self.actionMaterialDark.setText(QCoreApplication.translate("MainWindow", u"MaterialDark", None))
        self.efficientNetB2Action.setText(QCoreApplication.translate("MainWindow", u"EfficientNetB2", None))
#if QT_CONFIG(tooltip)
        self.efficientNetB2Action.setToolTip(QCoreApplication.translate("MainWindow", u"EfficientNetB2", None))
#endif // QT_CONFIG(tooltip)
#if QT_CONFIG(shortcut)
        self.efficientNetB2Action.setShortcut(QCoreApplication.translate("MainWindow", u"Ctrl+Alt+2", None))
#endif // QT_CONFIG(shortcut)
        self.groupBox.setTitle(QCoreApplication.translate("MainWindow", u"\u56fe\u7247\u5bfc\u5165\u4e0e\u5904\u7406", None))
#if QT_CONFIG(tooltip)
        self.imageLabel.setToolTip(QCoreApplication.translate("MainWindow", u"<html><head/><body><p>\u53cc\u51fb\u9009\u62e9\u6587\u4ef6</p><p><span style=\" font-weight:700;\">Ctrl-V </span>\u7c98\u8d34\u526a\u5207\u677f\u56fe\u7247</p></body></html>", None))
#endif // QT_CONFIG(tooltip)
        self.imageLabel.setText("")
#if QT_CONFIG(tooltip)
        self.nameEdit.setToolTip(QCoreApplication.translate("MainWindow", u"\u56fe\u7247\u540d\u79f0", None))
#endif // QT_CONFIG(tooltip)
        self.nameEdit.setPlaceholderText(QCoreApplication.translate("MainWindow", u"\u56fe\u7247\u540d\u79f0", None))
        self.label_2.setText(QCoreApplication.translate("MainWindow", u"\u8def\u5f84\uff1a", None))
#if QT_CONFIG(tooltip)
        self.chooseButton.setToolTip(QCoreApplication.translate("MainWindow", u"\u9009\u62e9\u56fe\u7247", None))
#endif // QT_CONFIG(tooltip)
        self.chooseButton.setText("")
#if QT_CONFIG(tooltip)
        self.resetButton.setToolTip(QCoreApplication.translate("MainWindow", u"\u6062\u590d\u539f\u56fe", None))
#endif // QT_CONFIG(tooltip)
        self.groupBox_5.setTitle(QCoreApplication.translate("MainWindow", u"\u82b1\u6735\u56fe\u50cf\u8bc6\u522b", None))
#if QT_CONFIG(tooltip)
        self.predictButton.setToolTip(QCoreApplication.translate("MainWindow", u"<html><head/><body><p>\u5f00\u59cb<span style=\" font-weight:700;\">AI</span>\u8bc6\u522b</p><p>(\u9996\u6b21\u8bc6\u522b\u53ef\u80fd\u82b1\u8d39\u8f83\u957f\u65f6\u95f4)</p></body></html>", None))
#endif // QT_CONFIG(tooltip)
        self.predictButton.setText(QCoreApplication.translate("MainWindow", u"\u8bc6\u522b", None))
        self.resultLabel.setText("")
        self.resultLabel_2.setText("")
#if QT_CONFIG(tooltip)
        self.clearButton.setToolTip(QCoreApplication.translate("MainWindow", u"\u6e05\u7a7a\u5bfc\u5165", None))
#endif // QT_CONFIG(tooltip)
        self.clearButton.setText("")
#if QT_CONFIG(shortcut)
        self.clearButton.setShortcut(QCoreApplication.translate("MainWindow", u"Backspace", None))
#endif // QT_CONFIG(shortcut)
#if QT_CONFIG(tooltip)
        self.cutButton.setToolTip(QCoreApplication.translate("MainWindow", u"\u6253\u5f00\u56fe\u7247\u5904\u7406\u5668", None))
#endif // QT_CONFIG(tooltip)
#if QT_CONFIG(tooltip)
        self.imageTextEdit.setToolTip(QCoreApplication.translate("MainWindow", u"\u56fe\u7247\u4fe1\u606f", None))
#endif // QT_CONFIG(tooltip)
        self.imageTextEdit.setPlaceholderText(QCoreApplication.translate("MainWindow", u"\u672a\u5bfc\u5165\u56fe\u7247", None))
        self.tabWidget_2.setTabText(self.tabWidget_2.indexOf(self.tab), QCoreApplication.translate("MainWindow", u"\u56fe\u7247\u4fe1\u606f", None))
#if QT_CONFIG(tooltip)
        self.saveButton.setToolTip(QCoreApplication.translate("MainWindow", u"\u4fdd\u5b58\u9884\u5904\u7406\u56fe\u7247", None))
#endif // QT_CONFIG(tooltip)
        self.saveButton.setText(QCoreApplication.translate("MainWindow", u"\u4fdd\u5b58\u56fe\u7247", None))
#if QT_CONFIG(tooltip)
        self.saveNameEdit.setToolTip(QCoreApplication.translate("MainWindow", u"\u9ed8\u8ba4\u4e3a\u5bfc\u5165\u540d\u79f0", None))
#endif // QT_CONFIG(tooltip)
        self.saveNameEdit.setPlaceholderText(QCoreApplication.translate("MainWindow", u"\u6587\u4ef6\u540d\u542b\u6269\u5c55\u540d", None))
        self.label_3.setText(QCoreApplication.translate("MainWindow", u"\u6587\u4ef6\u540d\uff1a", None))
#if QT_CONFIG(tooltip)
        self.savePathTextEdit.setToolTip(QCoreApplication.translate("MainWindow", u"\u9ed8\u8ba4\u4e3a\u5bfc\u5165\u8def\u5f84", None))
#endif // QT_CONFIG(tooltip)
        self.savePathTextEdit.setPlaceholderText(QCoreApplication.translate("MainWindow", u"\u4fdd\u5b58\u8def\u5f84", None))
        self.label_5.setText(QCoreApplication.translate("MainWindow", u"\u4fdd\u5b58\u8def\u5f84\uff1a", None))
#if QT_CONFIG(tooltip)
        self.getDirectoryButton_2.setToolTip(QCoreApplication.translate("MainWindow", u"\u9009\u62e9\u6587\u4ef6\u5939", None))
#endif // QT_CONFIG(tooltip)
        self.getDirectoryButton_2.setText("")
        self.comboBox.setItemText(0, QCoreApplication.translate("MainWindow", u"\u9ed8\u8ba4\u6269\u5c55\u540d", None))
        self.comboBox.setItemText(1, QCoreApplication.translate("MainWindow", u"jpeg", None))
        self.comboBox.setItemText(2, QCoreApplication.translate("MainWindow", u"png", None))
        self.comboBox.setItemText(3, QCoreApplication.translate("MainWindow", u"bmp", None))
        self.comboBox.setItemText(4, QCoreApplication.translate("MainWindow", u"gif", None))
        self.comboBox.setItemText(5, QCoreApplication.translate("MainWindow", u"tiff", None))
        self.comboBox.setItemText(6, QCoreApplication.translate("MainWindow", u"Webp", None))

#if QT_CONFIG(tooltip)
        self.comboBox.setToolTip(QCoreApplication.translate("MainWindow", u"<html><head/><body><p>\u9009\u62e9<span style=\" font-weight:700;\">\u6587\u4ef6\u6269\u5c55\u540d</span></p></body></html>", None))
#endif // QT_CONFIG(tooltip)
        self.comboBox.setPlaceholderText(QCoreApplication.translate("MainWindow", u"\u9009\u62e9\u6269\u5c55\u540d", None))
        self.comboBox_2.setItemText(0, QCoreApplication.translate("MainWindow", u"\u9ed8\u8ba4\u8272\u5f69\u6a21\u5f0f", None))
        self.comboBox_2.setItemText(1, QCoreApplication.translate("MainWindow", u"1", None))
        self.comboBox_2.setItemText(2, QCoreApplication.translate("MainWindow", u"L", None))
        self.comboBox_2.setItemText(3, QCoreApplication.translate("MainWindow", u"RGB", None))
        self.comboBox_2.setItemText(4, QCoreApplication.translate("MainWindow", u"RGBA", None))
        self.comboBox_2.setItemText(5, QCoreApplication.translate("MainWindow", u"HSV", None))
        self.comboBox_2.setItemText(6, QCoreApplication.translate("MainWindow", u"CMYK", None))

#if QT_CONFIG(tooltip)
        self.comboBox_2.setToolTip(QCoreApplication.translate("MainWindow", u"<html><head/><body><p>\u9009\u62e9<span style=\" font-weight:700;\">\u8272\u5f69\u6a21\u5f0f</span></p></body></html>", None))
#endif // QT_CONFIG(tooltip)
        self.comboBox_2.setPlaceholderText(QCoreApplication.translate("MainWindow", u"\u9009\u62e9\u8272\u5f69\u6a21\u5f0f", None))
        self.label_6.setText(QCoreApplication.translate("MainWindow", u"\u00d7", None))
        self.label_res.setText(QCoreApplication.translate("MainWindow", u"\u5206\u8fa8\u7387\uff1a", None))
        self.tabWidget_2.setTabText(self.tabWidget_2.indexOf(self.tab_2), QCoreApplication.translate("MainWindow", u"\u4fdd\u5b58\u56fe\u7247", None))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab1), QCoreApplication.translate("MainWindow", u"\u82b1\u6735\u9884\u6d4b", None))
        ___qtablewidgetitem = self.tableWidget.horizontalHeaderItem(0)
        ___qtablewidgetitem.setText(QCoreApplication.translate("MainWindow", u"\u56fe\u7247\u8def\u5f84", None));
        ___qtablewidgetitem1 = self.tableWidget.horizontalHeaderItem(1)
        ___qtablewidgetitem1.setText(QCoreApplication.translate("MainWindow", u"\u56fe\u7247\u540d\u79f0", None));
        ___qtablewidgetitem2 = self.tableWidget.horizontalHeaderItem(2)
        ___qtablewidgetitem2.setText(QCoreApplication.translate("MainWindow", u"\u82b1\u6735\u9884\u6d4b\u7ed3\u679c", None));
#if QT_CONFIG(whatsthis)
        self.tableWidget.setWhatsThis("")
#endif // QT_CONFIG(whatsthis)
#if QT_CONFIG(tooltip)
        self.clearTableButton.setToolTip(QCoreApplication.translate("MainWindow", u"\u4e00\u952e\u6e05\u7a7a", None))
#endif // QT_CONFIG(tooltip)
        self.clearTableButton.setText("")
        self.groupBox_2.setTitle(QCoreApplication.translate("MainWindow", u"\u82b1\u6735\u56fe\u50cf\u6279\u91cf\u64cd\u4f5c", None))
        self.batchPredictButton.setText(QCoreApplication.translate("MainWindow", u"\u82b1\u6735\u6279\u91cf\u9884\u6d4b", None))
        self.label.setText(QCoreApplication.translate("MainWindow", u"\u4fdd\u5b58\u8def\u5f84\uff1a", None))
#if QT_CONFIG(tooltip)
        self.savePathLineEdit.setToolTip(QCoreApplication.translate("MainWindow", u"\u8f93\u5165\u4fdd\u5b58\u8def\u5f84", None))
#endif // QT_CONFIG(tooltip)
#if QT_CONFIG(tooltip)
        self.getDirectoryButton.setToolTip(QCoreApplication.translate("MainWindow", u"\u9009\u62e9\u4fdd\u5b58\u8def\u5f84", None))
#endif // QT_CONFIG(tooltip)
        self.getDirectoryButton.setText(QCoreApplication.translate("MainWindow", u"...", None))
#if QT_CONFIG(tooltip)
        self.batchExportButton.setToolTip(QCoreApplication.translate("MainWindow", u"\u4ee5\u6587\u4ef6\u5939\u65b9\u5f0f\u6279\u91cf\u5bfc\u51fa", None))
#endif // QT_CONFIG(tooltip)
        self.batchExportButton.setText(QCoreApplication.translate("MainWindow", u"\u7ed3\u679c\u5bfc\u51fa", None))
#if QT_CONFIG(tooltip)
        self.convertModeCheckBox.setToolTip(QCoreApplication.translate("MainWindow", u"<html><head/><body><p>\u5c06\u56fe\u7247\u8f6c\u6362\u4e3a<span style=\" font-weight:700; color:#ff0000;\">R</span><span style=\" font-weight:700; color:#00ff00;\">G</span><span style=\" font-weight:700; color:#0000ff;\">B</span><span style=\" color:#000000;\">\u8272\u5f69\u6a21\u5f0f\u5e76\u4ee5JPG\u683c\u5f0f\u4fdd\u5b58</span></p></body></html>", None))
#endif // QT_CONFIG(tooltip)
        self.convertModeCheckBox.setText(QCoreApplication.translate("MainWindow", u"RGB+JPG", None))
#if QT_CONFIG(tooltip)
        self.batchRenameCheckBox.setToolTip(QCoreApplication.translate("MainWindow", u"\u4ee5\u9884\u6d4b\u7684\u5206\u7c7b\u7ed3\u679c\u547d\u540d\uff1asunflower.jpg", None))
#endif // QT_CONFIG(tooltip)
        self.batchRenameCheckBox.setText(QCoreApplication.translate("MainWindow", u"\u91cd\u547d\u540d", None))
        self.label_res_2.setText(QCoreApplication.translate("MainWindow", u"\u5206\u8fa8\u7387\uff1a", None))
        self.label_9.setText(QCoreApplication.translate("MainWindow", u"\u00d7", None))
        self.batchImportLabel.setText("")
#if QT_CONFIG(tooltip)
        self.batchChooseButton.setToolTip(QCoreApplication.translate("MainWindow", u"\u6279\u91cf\u5bfc\u5165", None))
#endif // QT_CONFIG(tooltip)
        self.batchChooseButton.setText("")
#if QT_CONFIG(tooltip)
        self.statisticsTextEdit.setToolTip(QCoreApplication.translate("MainWindow", u"\u9884\u6d4b\u4fe1\u606f\u5c55\u793a", None))
#endif // QT_CONFIG(tooltip)
#if QT_CONFIG(tooltip)
        self.statisticsButton.setToolTip(QCoreApplication.translate("MainWindow", u"\u67f1\u72b6\u5806\u53e0\u56fe\u7edf\u8ba1\u4fe1\u606f", None))
#endif // QT_CONFIG(tooltip)
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab2), QCoreApplication.translate("MainWindow", u"\u6279\u91cf\u9884\u6d4b", None))
        self.menu.setTitle(QCoreApplication.translate("MainWindow", u"\u6587\u4ef6(&F)", None))
        self.menu_2.setTitle(QCoreApplication.translate("MainWindow", u"\u5e2e\u52a9(&H)", None))
        self.menu_style.setTitle(QCoreApplication.translate("MainWindow", u"\u4e3b\u9898\u98ce\u683c", None))
        self.menu_M.setTitle(QCoreApplication.translate("MainWindow", u"\u6a21\u578b(&M)", None))
        self.toolBar.setWindowTitle(QCoreApplication.translate("MainWindow", u"toolBar", None))
    # retranslateUi

